app.config(['$translateProvider',
      function($translateProvider) {
            $translateProvider.translations('en', {
                  //global
                  global_addNew: 'Add New',
                  global_actions: 'Actions',
                  global_descriptionEN: 'Description EN',
                  global_descriptionFR: 'Description FR',
                  global_sortingSequence: 'Sorting sequence',
                  global_successOperation: 'Operation finished successfully.',
                  global_errorOperation: 'Operation failed.',
                  global_noDefaultViewForTheRole: 'Contact your system administrator (No default view assignment to the role)',
                  global_noCompanyAssignment: 'Contact your system administrator (No company assignment to the user)',
                  global_noRoleAssignment: 'Contact your system administrator (No role assignment to the user)',
                  global_noInitialPasswordProvided: 'No initial password has been provided. User creation is not possible',
                  global_changesSaveConfirmationHeader: 'Do you want to save changes before leaving the view?',
                  global_changesSaveConfirmationContent: 'Not saved changes will be lost...',
                  global_emptyFields: 'Please make sure that all the fields are filled',
                  global_companies: 'Assigned Companies:',
                  global_authorizedPhases: 'Authorized projects and phases:',
                  global_avatar: 'Avatar:',
                  global_noTableData: 'No data selected',
                  global_createdBy: 'Created By',
                  global_createdAt: 'Created At',
                  global_role: 'Role',
                  global_company: 'Company',
                  global_roles: 'Role(s)',
                  global_companies: 'Company(s)',
                  global_project: 'Project',
                  global_upload: 'Upload',
                  global_icon: 'Icon',
                  global_userName: 'Username',
                  global_email: 'Email',
                  global_back: 'Back',
                  global_edit: 'Edit',
                  global_save: 'Save',
                  global_delete: 'Delete',
                  global_saveAndNew: 'Save and new',
                  global_creationDate: 'Creation Date',
                  global_lastModificationDate: 'Last Modification Date',
                  global_associatedIconFileGuid: 'Associated Icon File Guid',
                  global_associatedColor: 'Associated Color',
                  global_password: 'Password',
                  global_passwordConfirmation: 'Password Confirmation',
                  global_continue: 'Continue',
                  global_ok: 'Ok',
                  global_yes: 'Yes',
                  global_no: 'No',
                  global_cancel: 'Cancel',
                  global_passwordsDontMatch: "Provided passwords don't match.",
                  global_contractorName: 'Contractor',
                  global_clientName: 'Client',
                  global_phone: 'Phone',
                  global_tags: 'Tags',
                  global_name: 'Name',
                  global_title: 'Title',
                  global_secondaryPhone: 'Secondary Phone',
                  global_website: "Website",
                  global_fax: 'Fax',
                  global_associatedPhases: 'Associated projects and phases:',
                  global_selectedProjectsAndPhases: 'Select Project(s) - Phase(s)',
                  global_billingStreet: 'Billing street',
                  global_billingCity: 'Billing city',
                  global_billingPostalCode: 'Billing postal code',
                  global_billingCountry: 'Billing country:',
                  global_billingProvince: 'Billing state/province:',
                  global_shippingStreet: 'Shipping street',
                  global_shippingCity: 'Shipping city',
                  global_shippingPostalCode: 'Shipping postal code',
                  global_shippingCountry: 'Shipping country:',
                  global_shippingProvince: 'Shipping state/province:',
                  global_tags: "Tags",
                  global_addTag: "Add a tag",
                  global_contactType: "Contact Type:",
                  global_account: "Account",
                  global_selectCountry: "Select Country",
                  global_selectState: "Select Province/State",
                  //backendMessages
                  m100: 'Operation finished successfully.',
                  m101: 'Email with instructions to recover your password was successfully sent.',
                  m102: 'Your password was successfully changed.',
                  m200: 'Username already exists',
                  m201: 'User with provided email already exists',
                  m203: 'Can not login. Check your Username and Password.',
                  m204: 'Email not found.',
                  m205: 'Provided Old Password is not correct',
                  m206: 'Username not found',
                  //app
                  app_switchCompanies: "Switch Company",
                  app_switchRoles: "Switch Role",
                  app_logOut: 'Log Out',
                  app_adminPanel: 'Admin Panel',
                  app_profileSettings: 'Profile Settings',
                  app_deficienciesTab: 'Deficiencies',
                  app_unitsTab: 'Units',
                  app_contractorsTab: 'Contractors',
                  app_clientsTab: 'Clients',
                  app_contactsTab: "Contacts",
                  //profileSettings
                  profileSettings_menuHeader: 'Profile Settings Menu',
                  profileSettings_profileDetails: 'Profile Details',
                  profileSettings_changePassword: 'Change Password',
                  //profileDetails
                  profileDetails_title: 'Profile Details',
                  //changePassword
                  changePassword_title: 'Change Password',
                  //adminPanel
                  adminPanel_menuHeader: 'Admin Panel Menu',
                  adminPanel_companies: "Companies",
                  adminPanel_userManagement: 'User Management',
                  adminPanel_roles: "User Roles",
                  adminPanel_projects: 'Projects',
                  adminPanel_projectDefaultLabel: 'Select Project',
                  adminPanel_phases: 'Phases',
                  adminPanel_deficiencyStatuses: 'Deficiency Statuses',
                  adminPanel_deficiencyStatusIconDefaultLabel: 'Select Icon',
                  adminPanel_deficiencyPriorities: 'Deficiency Priorities',
                  adminPanel_systemFiles: 'System Files',
                  adminPanel_operationLogs: 'Operation Logs',
                  adminPanel_accountTypes: 'Account Types',
                  adminPanel_contactTypes: 'Contact Types',
                  adminPanel_hideSidenav: 'Open Admin Panel Menu',
                  //companiesList
                  companiesList_title: "Companies",
                  companiesList_companyName: "Company Name",
                  //usersList
                  usersList_title: 'Users List',
                  //userDetails
                  userDetails_title: 'User Details',
                  userDetails_deletionConfirmationHeader: 'Are you sure that you want to delete current user?',
                  userDetails_deletionConfirmationContent: 'Current user will be deleted...',
                  userDetails_username: 'Username:',
                  userDetails_password: 'Password:',
                  userDetails_passwordConfirmation: 'Password Confirmation:',
                  userDetails_email: 'Email:',
                  userDetails_associatedCompanies: 'Associated Companies:',
                  userDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  userDetails_associatedRoles: 'Roles:',
                  userDetails_avatar: 'Profile Picture:', 
                  //rolesList
                  rolesList_title: "User Roles",
                  rolesList_roleName: "Role Name",
                  //projectsList
                  projectsList_title: 'Projects',
                  //phasesList
                  phasesList_title: 'Phases',
                  //deficiencyStatuses
                  deficiencyStatuses_title: 'Deficiency Statuses',
                  //deficiencyPriorities
                  deficiencyPriorities_title: 'Deficiency Priorities',
                  //operationLogsList
                  operationLogsList_title: 'Operation Logs',
                  operationLogsList_operationName: 'Operation Name',
                  operationLogsList_operationContent: 'Operation Content',
                  //accountTypesList
                  accountTypesList_title: 'Account Types',
                  //contactTypesList
                  contactTypesList_title: 'Contact Types',
                  //systemFiles
                  systemFiles_title: 'System Files',
                  systemFiles_logos: 'Logos',
                  systemFiles_logo: 'Logo',
                  systemFiles_deficiencyStatusIcon: 'Deficiency Status Icons',
                  systemFiles_Icon: 'Icon',
                  //signIn
                  signIn_userName: 'Username',
                  signIn_password: 'Password',
                  signIn_logIn: 'Log In to Conspector',
                  signIn_languageCode: 'FR',
                  signIn_forgotPassword: 'Forgot your password?',
                  signIn_rememberUserName: 'Remember Username',
                  //initialPasswordReset
                  initialPasswordReset_headerLabel: 'This is the first time you login. Please enter a new password:',
                  initialPasswordReset_newPassword: 'New password',
                  initialPasswordReset_newPasswordConfirmation: 'New password confirmation',
                  initialPasswordReset_reset: 'Set new password',
                  //passwordReset
                  passwordReset_headerLabel: 'Please enter a new password:',
                  passwordReset_newPassword: 'New password',
                  passwordReset_newPasswordConfirmation: 'New password confirmation',
                  passwordReset_reset: 'Set new password',
                  passwordReset_passwordsDontMatch: "Provided passwords don't match.",
                  //companySelection
                  companySelection_heagerLabel: 'Please choose a company:',
                  //roleSelection
                  roleSelection_heagerLabel: 'Please choose a role:',
                  //forgotPassword
                  forgotPassword_heagerLabel: 'Please select what you remember:',
                  forgotPassword_userName: 'Username',
                  forgotPassword_email: 'Email',
                  forgotPassword_reset: 'Reset password',
                  forgotPassword_footerLabel: 'Having issues logging in?\nEmail us at ',
                  //contractorsList
                  contractorsList_title: 'Contractors List',
                  contractorsList_addNew: 'Add Contractor',
                  //contractorDetails
                  contractorDetails_title: 'Contractor Details',
                  contractorDetails_deletionConfirmationHeader: 'You are about to delete a contractor account.',
                  contractorDetails_deletionConfirmationContent: 'Are you sure you want to proceed ? All related contacts will be erased.',
                  contractorDetails_name: 'Name:',
                  contractorDetails_phone: 'Phone:',
                  contractorDetails_secondaryPhone: 'Secondary Phone:',
                  contractorDetails_website: 'Website:',
                  contractorDetails_email: 'Email:',
                  contractorDetails_fax: 'Fax:',
                  contractorDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  contractorDetails_descriptionTags: 'Description Tags:',
                  contractorDetails_billingStreet: 'Billing Street:',
                  contractorDetails_billingCity: 'Billing City:',
                  contractorDetails_billingPostalCode: 'Postal Code/ZIP:',
                  contractorDetails_billingCountry: 'Billing Country:',
                  contractorDetails_billingState: 'Billing State/Province:',
                  contractorDetails_shippingStreet: 'Shipping Street:',
                  contractorDetails_shippingCity: 'Shipping City:',
                  contractorDetails_shippingPostalCode: 'Postal Code/ZIP:',
                  contractorDetails_shippingCountry: 'Shipping Country:',
                  contractorDetails_shippingState: 'Shipping State/Province:',
                  //contactsList
                  contactsList_title: 'Contacts List',
                  contactDetails_title: 'Contact Details',
                  contactsList_addNew: 'Add Contact',
                  //contactDetails
                  contactDetails_title: 'Contact Details',
                  contactDetails_deletionConfirmationHeader: 'You are about to delete a contact.',
                  contactDetails_deletionConfirmationContent: 'Are you sure you want to proceed ?',
                  contactDetails_name: 'Name:',
                  contactDetails_lastName: 'Last Name:',
                  contactDetails_personTitle: 'Title:',
                  contactDetails_homePhone: 'Phone:',
                  contactDetails_workPhone: 'Secondary Phone:',
                  contactDetails_mobilePhone: 'Mobile Phone:',
                  contactDetails_email: 'Email:',
                  contactDetails_fax: 'Fax:',
                  contactDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  contactDetails_associatedParentAccount: 'Parent Account:',
                  contactDetails_selectParentAccount: 'Select Parent Account:',
                  contactDetails_contactType: 'Contact Type:',
                  contactDetails_selectContactType: 'Select Contact Type:',
                  contactDetails_descriptionTags: 'Description Tags:',
                  contactDetails_billingStreet: 'Billing Street:',
                  contactDetails_billingCity: 'Billing City:',
                  contactDetails_billingPostalCode: 'Postal Code/ZIP:',
                  contactDetails_billingCountry: 'Billing Country:',
                  contactDetails_billingState: 'Billing State/Province:',
                  contactDetails_shippingStreet: 'Shipping Street:',
                  contactDetails_shippingCity: 'Shipping City:',
                  contactDetails_shippingPostalCode: 'Postal Code/ZIP:',
                  contactDetails_shippingCountry: 'Shipping Country:',
                  contactDetails_shippingState: 'Shipping State/Province:',
                  //clientsList
                  clientsList_title: 'Clients List',
                  clientsList_addNew: 'Add Client Account',
                  //clientDetails
                  clientDetails_title: 'Client Details',
                  clientDetails_deletionConfirmationHeader: 'You are about to delete a client account.',
                  clientDetails_deletionConfirmationContent: 'Are you sure you want to proceed ? All related contacts will be erased.',
                  clientDetails_name: 'Name:',
                  clientDetails_phone: 'Phone:',
                  clientDetails_secondaryPhone: 'Secondary Phone:',
                  clientDetails_website: 'Website:',
                  clientDetails_email: 'Email:',
                  clientDetails_fax: 'Fax:',
                  clientDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  clientDetails_descriptionTags: 'Description Tags:',
                  clientDetails_billingStreet: 'Billing Street:',
                  clientDetails_billingCity: 'Billing City:',
                  clientDetails_billingPostalCode: 'Postal Code/ZIP:',
                  clientDetails_billingCountry: 'Billing Country:',
                  clientDetails_billingState: 'Billing State/Province:',
                  clientDetails_shippingStreet: 'Shipping Street:',
                  clientDetails_shippingCity: 'Shipping City:',
                  clientDetails_shippingPostalCode: 'Postal Code/ZIP:',
                  clientDetails_shippingCountry: 'Shipping Country:',
                  clientDetails_shippingState: 'Shipping State/Province:',
            });

            $translateProvider.translations('fr', {
                  //global
                  global_addNew: 'Add New',
                  global_actions: 'Actions',
                  global_descriptionEN: 'Description EN',
                  global_descriptionFR: 'Description FR',
                  global_sortingSequence: 'Sorting sequence',
                  global_successOperation: 'Operation finished successfully.',
                  global_errorOperation: 'Operation failed.',
                  global_noDefaultViewForTheRole: 'Contact your system administrator (No default view assignment to the role)',
                  global_noCompanyAssignment: 'Contact your system administrator (No company assignment to the user)',
                  global_noRoleAssignment: 'Contact your system administrator (No role assignment to the user)',
                  global_noInitialPasswordProvided: 'No initial password has been provided. User creation is not possible',
                  global_changesSaveConfirmationHeader: 'Do you want to save changes before leaving the view?',
                  global_changesSaveConfirmationContent: 'Not saved changes will be lost...',
                  global_emptyFields: 'Please make sure that all the fields are filled',
                  global_companies: 'Assigned Companies:',
                  global_authorizedPhases: 'Authorized projects and phases:',
                  global_avatar: 'Avatar:',
                  global_noTableData: 'No data selected',
                  global_createdBy: 'Created By',
                  global_createdAt: 'Created At',
                  global_role: 'Role',
                  global_company: 'Company',
                  global_roles: 'Role(s)',
                  global_companies: 'Company(s)',
                  global_project: 'Project',
                  global_upload: 'Upload',
                  global_icon: 'Icon',
                  global_userName: 'Username',
                  global_email: 'Email',
                  global_back: 'Back',
                  global_edit: 'Edit',
                  global_save: 'Save',
                  global_delete: 'Delete',
                  global_saveAndNew: 'Save and new',
                  global_creationDate: 'Creation Date',
                  global_lastModificationDate: 'Last Modification Date',
                  global_associatedIconFileGuid: 'Associated Icon File Guid',
                  global_associatedColor: 'Associated Color',
                  global_password: 'Password',
                  global_passwordConfirmation: 'Password Confirmation',
                  global_continue: 'Continue',
                  global_ok: 'Ok',
                  global_yes: 'Yes',
                  global_no: 'No',
                  global_cancel: 'Cancel',
                  global_passwordsDontMatch: "Provided passwords don't match.",
                  global_contractorName: 'Contractor',
                  global_clientName: 'Client',
                  global_phone: 'Phone',
                  global_tags: 'Tags',
                  global_name: 'Name',
                  global_title: 'Title',
                  global_secondaryPhone: 'Secondary Phone',
                  global_website: "Website",
                  global_fax: 'Fax',
                  global_associatedPhases: 'Associated projects and phases:',
                  global_selectedProjectsAndPhases: 'Select Project(s) - Phase(s)',
                  global_billingStreet: 'Billing street',
                  global_billingCity: 'Billing city',
                  global_billingPostalCode: 'Billing postal code',
                  global_billingCountry: 'Billing country:',
                  global_billingProvince: 'Billing state/province:',
                  global_shippingStreet: 'Shipping street',
                  global_shippingCity: 'Shipping city',
                  global_shippingPostalCode: 'Shipping postal code',
                  global_shippingCountry: 'Shipping country:',
                  global_shippingProvince: 'Shipping state/province:',
                  global_tags: "Tags",
                  global_addTag: "Add a tag",
                  global_contactType: "Contact Type:",
                  global_account: "Account",
                  global_selectCountry: "Select Country",
                  global_selectState: "Select Province/State",
                  //backendMessages
                  m100: 'Operation finished successfully.',
                  m101: 'Email with instructions to recover your password was successfully sent.',
                  m102: 'Your password was successfully changed.',
                  m200: 'Username already exists',
                  m201: 'User with provided email already exists',
                  m203: 'Can not login. Check your Username and Password.',
                  m204: 'Email not found.',
                  m205: 'Provided Old Password is not correct',
                  m206: 'Username not found',
                  //app
                  app_switchCompanies: "Switch Company",
                  app_switchRoles: "Switch Role",
                  app_logOut: 'Log Out',
                  app_adminPanel: 'Admin Panel',
                  app_profileSettings: 'Profile Settings',
                  app_deficienciesTab: 'Deficiencies',
                  app_unitsTab: 'Units',
                  app_contractorsTab: 'Contractors',
                  app_clientsTab: 'Clients',
                  app_contactsTab: "Contacts",
                  //profileSettings
                  profileSettings_menuHeader: 'Profile Settings Menu',
                  profileSettings_profileDetails: 'Profile Details',
                  profileSettings_changePassword: 'Change Password',
                  //profileDetails
                  profileDetails_title: 'Profile Details',
                  //changePassword
                  changePassword_title: 'Change Password',
                  //adminPanel
                  adminPanel_menuHeader: 'Admin Panel Menu',
                  adminPanel_companies: "Companies",
                  adminPanel_userManagement: 'User Management',
                  adminPanel_roles: "User Roles",
                  adminPanel_projects: 'Projects',
                  adminPanel_projectDefaultLabel: 'Select Project',
                  adminPanel_phases: 'Phases',
                  adminPanel_deficiencyStatuses: 'Deficiency Statuses',
                  adminPanel_deficiencyStatusIconDefaultLabel: 'Select Icon',
                  adminPanel_deficiencyPriorities: 'Deficiency Priorities',
                  adminPanel_systemFiles: 'System Files',
                  adminPanel_operationLogs: 'Operation Logs',
                  adminPanel_accountTypes: 'Account Types',
                  adminPanel_contactTypes: 'Contact Types',
                  adminPanel_hideSidenav: 'Open Admin Panel Menu',
                  //companiesList
                  companiesList_title: "Companies",
                  companiesList_companyName: "Company Name",
                  //usersList
                  usersList_title: 'Users List',
                  //userDetails
                  userDetails_title: 'User Details',
                  userDetails_deletionConfirmationHeader: 'Are you sure that you want to delete current user?',
                  userDetails_deletionConfirmationContent: 'Current user will be deleted...',
                  userDetails_username: 'Username:',
                  userDetails_password: 'Password:',
                  userDetails_passwordConfirmation: 'Password Confirmation:',
                  userDetails_email: 'Email:',
                  userDetails_associatedCompanies: 'Associated Companies:',
                  userDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  userDetails_associatedRoles: 'Roles:',
                  userDetails_avatar: 'Profile Picture:',
                  //rolesList
                  rolesList_title: "User Roles",
                  rolesList_roleName: "Role Name",
                  //projectsList
                  projectsList_title: 'Projects',
                  //phasesList
                  phasesList_title: 'Phases',
                  //deficiencyStatuses
                  deficiencyStatuses_title: 'Deficiency Statuses',
                  //deficiencyPriorities
                  deficiencyPriorities_title: 'Deficiency Priorities',
                  //operationLogsList
                  operationLogsList_title: 'Operation Logs',
                  operationLogsList_operationName: 'Operation Name',
                  operationLogsList_operationContent: 'Operation Content',
                  //accountTypesList
                  accountTypesList_title: 'Account Types',
                  //contactTypesList
                  contactTypesList_title: 'Contact Types',
                  //systemFiles
                  systemFiles_title: 'System Files',
                  systemFiles_logos: 'Logos',
                  systemFiles_logo: 'Logo',
                  systemFiles_deficiencyStatusIcon: 'Deficiency Status Icons',
                  systemFiles_Icon: 'Icon',
                  //signIn
                  signIn_userName: 'Username',
                  signIn_password: 'Password',
                  signIn_logIn: 'Connexion \u00E0 Conspector',
                  signIn_languageCode: 'EN',
                  signIn_forgotPassword: 'Forgot your password?',
                  signIn_rememberUserName: 'Remember Username',
                  //initialPasswordReset
                  initialPasswordReset_headerLabel: 'This is the first time you login. Please enter a new password:',
                  initialPasswordReset_newPassword: 'New password',
                  initialPasswordReset_newPasswordConfirmation: 'New password confirmation',
                  initialPasswordReset_reset: 'Set new password',
                  //passwordReset
                  passwordReset_headerLabel: 'Please enter a new password:',
                  passwordReset_newPassword: 'New password',
                  passwordReset_newPasswordConfirmation: 'New password confirmation',
                  passwordReset_reset: 'Set new password',
                  passwordReset_passwordsDontMatch: "Provided passwords don't match.",
                  //companySelection
                  companySelection_heagerLabel: 'Please choose a company:',
                  //roleSelection
                  roleSelection_heagerLabel: 'Please choose a role:',
                  //forgotPassword
                  forgotPassword_heagerLabel: 'Please select what you remember:',
                  forgotPassword_userName: 'Username',
                  forgotPassword_email: 'Email',
                  forgotPassword_reset: 'Reset password',
                  forgotPassword_footerLabel: 'Un probl\u00E8me de connexion?\n\u00C9crivez \u00E0 ',
                  //contractorsList
                  contractorsList_title: 'Contractors List',
                  contractorsList_addNew: 'Add Contractor',
                  //contractorDetails
                  contractorDetails_title: 'Contractor Details',
                  contractorDetails_deletionConfirmationHeader: 'You are about to delete a client account.',
                  contractorDetails_deletionConfirmationContent: 'Are you sure you want to proceed ? All related contacts will be erased.',
                  contractorDetails_name: 'Name:',
                  contractorDetails_phone: 'Phone:',
                  contractorDetails_secondaryPhone: 'Secondary Phone:',
                  contractorDetails_website: 'Website:',
                  contractorDetails_email: 'Email:',
                  contractorDetails_fax: 'Fax:',
                  contractorDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  contractorDetails_descriptionTags: 'Description Tags:',
                  contractorDetails_billingStreet: 'Billing Street:',
                  contractorDetails_billingCity: 'Billing City:',
                  contractorDetails_billingPostalCode: 'Postal Code/ZIP:',
                  contractorDetails_billingCountry: 'Billing Country:',
                  contractorDetails_billingState: 'Billing State/Province:',
                  contractorDetails_shippingStreet: 'Shipping Street:',
                  contractorDetails_shippingCity: 'Shipping City:',
                  contractorDetails_shippingPostalCode: 'Postal Code/ZIP:',
                  contractorDetails_shippingCountry: 'Shipping Country:',
                  contractorDetails_shippingState: 'Shipping State/Province:',
                  //contactsList
                  contactsList_title: 'Contacts List',
                  contactsList_addNew: 'Add Contact',
                  //contactDetails
                  contactDetails_title: 'Contact Details',
                  contactDetails_deletionConfirmationHeader: 'You are about to delete a contact.',
                  contactDetails_deletionConfirmationContent: 'Are you sure you want to proceed ?',
                  contactDetails_name: 'Name:',
                  contactDetails_lastName: 'Last Name:',
                  contactDetails_personTitle: 'Title:',
                  contactDetails_homePhone: 'Phone:',
                  contactDetails_workPhone: 'Secondary Phone:',
                  contactDetails_mobilePhone: 'Mobile Phone:',
                  contactDetails_email: 'Email:',
                  contactDetails_fax: 'Fax:',
                  contactDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  contactDetails_associatedParentAccount: 'Parent Account:',
                  contactDetails_selectParentAccount: 'Select Parent Account:',
                  contactDetails_contactType: 'Contact Type:',
                  contactDetails_selectContactType: 'Select Contact Type:',
                  contactDetails_descriptionTags: 'Description Tags:',
                  contactDetails_billingStreet: 'Billing Street:',
                  contactDetails_billingCity: 'Billing City:',
                  contactDetails_billingPostalCode: 'Postal Code/ZIP:',
                  contactDetails_billingCountry: 'Billing Country:',
                  contactDetails_billingState: 'Billing State/Province:',
                  contactDetails_shippingStreet: 'Shipping Street:',
                  contactDetails_shippingCity: 'Shipping City:',
                  contactDetails_shippingPostalCode: 'Postal Code/ZIP:',
                  contactDetails_shippingCountry: 'Shipping Country:',
                  contactDetails_shippingState: 'Shipping State/Province:',
                  //clientsList
                  clientsList_title: 'Clients List',
                  clientsList_addNew: 'Add Client Account',
                  //clientDetails
                  clientDetails_title: 'Client Details',
                  clientDetails_deletionConfirmationHeader: 'You are about to delete a client account.',
                  clientDetails_deletionConfirmationContent: 'Are you sure you want to proceed ? All related contacts will be erased.',
                  clientDetails_name: 'Name:',
                  clientDetails_phone: 'Phone:',
                  clientDetails_secondaryPhone: 'Secondary Phone:',
                  clientDetails_website: 'Website:',
                  clientDetails_email: 'Email:',
                  clientDetails_fax: 'Fax:',
                  clientDetails_associatedProjectsAndPhases: 'Associated Projects and Phases:',
                  clientDetails_descriptionTags: 'Description Tags:',
                  clientDetails_billingStreet: 'Billing Street:',
                  clientDetails_billingCity: 'Billing City:',
                  clientDetails_billingPostalCode: 'Postal Code/ZIP:',
                  clientDetails_billingCountry: 'Billing Country:',
                  clientDetails_billingState: 'Billing State/Province:',
                  clientDetails_shippingStreet: 'Shipping Street:',
                  clientDetails_shippingCity: 'Shipping City:',
                  clientDetails_shippingPostalCode: 'Postal Code/ZIP:',
                  clientDetails_shippingCountry: 'Shipping Country:',
                  clientDetails_shippingState: 'Shipping State/Province:',
            });

            $translateProvider.preferredLanguage('en');
            $translateProvider.useCookieStorage();
      }
]);